### ISSUE TITLE
[Bug] App crashes when trying to delete category 

### ISSUE THREAD

**Issue by korboybeats** [SerenaKit/Santander#15]
Device: M1 iPad Pro
iOS: 15.5b4

https://user-images.githubusercontent.com/80824905/201013275-f7bc5845-ad48-41aa-be32-ffa27912f6a9.MOV

**Comment by SerenaKit** [comment]
Sigh.. yeah, the sidebar list view is very buggy, I know why (it’s also why the type selection view is a bit buggy though that doesn’t crash) but I’m puzzled as to how to solve it, give me some time and I’ll probably figure it out within the release of the next major commit

**Comment by SerenaKit** [comment]
@korboybeats Fixed! try now

**Comment by korboybeats** [comment]
> @korboybeats Fixed! try now

It works 🙏
