### ISSUE TITLE
No write permission a8x ipad air 2

### ISSUE THREAD

**Issue by seropigeorgedev** [SerenaKit/Santander#18]
I have no write permission a8x ipad air 2 plz fix it says: 'file santander could not be in library' (also plz include a compiled build ipa and tipa for troll store)

**Comment by seropigeorgeguy** [comment]
nvm that /* sorry other acount. */ but when root helper enabled it will crash when u try to write

**Comment by seropigeorgeguy** [comment]
plz fix that

**Comment by SerenaKit** [comment]
When I feel like it
