### ISSUE TITLE
Assets.car icon issues

### ISSUE THREAD

**Issue by DARKZINMAKER2** [SerenaKit/Santander#19]
In assets.car if I put a png icon it has a background - Iphone 6s 15.1

**Comment by SerenaKit** [comment]
This is how CoreUI works, complain to Apple, not me.

**Comment by DARKZINMAKER2** [comment]
There would be no way around this , because my friend is ios 15.2.4 iphone 6s and the png images have no background when placed in the assets car , sorry if I'm being boring I'm a beginner :>

**Comment by DARKZINMAKER2** [comment]
![D31CF584-F0EB-447D-AA6C-1D62B34BA11E](https://user-images.githubusercontent.com/119215148/204155534-f12310a5-b17e-40fd-8f8a-e4b3bc91b8f9.jpeg)
