### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by IBH27I** [SerenaKit/Santander#23]
I get permission denied on iPhone 13 pro iOS 16.1.2. Any help?

**Comment by lovexiaofan123** [comment]
ios15.5 13pro max The same prompt Permission denied

**Comment by WillRRRR** [comment]
I have been facing the same issue too! iOS 16.2 on my iPhone 14 Pro Max!

**Comment by SerenaKit** [comment]
This is because there’s no root helper and you’re all on versions that a root helper wouldn’t even work on
