### ISSUE TITLE
Application names in Data and Shared folders in var/mobile/Containers

### ISSUE THREAD

**Issue by baziex** [SerenaKit/Santander#5]
Please add App Names in Data and Shared folders in var/mobile/Containers 📁
Filza having this option. So we can recognise app folders easily. 
I found the names in var/containers/Bundle folder.
Same thing can be added in Data and Shared folders. Thank you

**Comment by SerenaKit** [comment]
Shared folder? Can you send the exact path to the shared folder? Unfortunately I don’t have a jailbroken device

**Comment by baziex** [comment]
1. /var/mobile/Containers/Data/Application 
![image](https://user-images.githubusercontent.com/30050582/188419904-285af02a-8b59-401b-a5c0-01ca7d137525.png)

2. /var/mobile/Containers/Shared/AppGroup
![image](https://user-images.githubusercontent.com/30050582/188420156-96b02211-c272-431f-a787-f960981b9a24.png)

These are the folders I mean.
Thank you.

**Comment by baziex** [comment]
I found App names in 
/var/containers/Bundle/Application
![image](https://user-images.githubusercontent.com/30050582/188420792-3e3b4b13-66c0-46af-86b9-5bc855807c4d.png)

Exactly like this I mean for the other folders I mentioned in above comment.

**Comment by SerenaKit** [comment]
Try this: https://github.com/SerenaKit/Santander/actions/runs/2992758680

**Comment by baziex** [comment]
Actually I'm also not having a Jailbroken device.
I'm using SantanderTS version of Nebula and installed using TrollStore. 

So this IPA I cannot test because it will not have permissions to Containers folder. 
By the way can you push these changes in Santander TrollStore version?

**Comment by baziex** [comment]
Okay thank you brother

**Comment by itsnebulalol** [comment]
I’ll merge the changes in a bit

**Comment by itsnebulalol** [comment]
Grab the latest action build [here](https://github.com/itsnebulalol/SantanderTS/actions/runs/2993691985).

**Comment by baziex** [comment]
I took latest build.
Now I can see Application Names in /var/mobile/Containers/Data/Application folder.

But not in /var/mobile/Containers/Shared/AppGroup folder.
If possible add the same in this directory too. Thank you.

**Comment by itsnebulalol** [comment]
I think the build i linked is out of date, did you get the latest from the actions tab? [Here](https://nightly.link/itsnebulalol/SantanderTS/suites/8143697553/artifacts/353174496) is the link if you need it.

**Comment by SerenaKit** [comment]
> 

Not sure how to fix this, don’t know what UUIDs are used there
